FROM php:8.1.0-cli
COPY sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install --allow-downgrades -y zlib1g=1:1.2.11.dfsg-1+deb10u1 zlib1g-dev
COPY grpc-1.46.3.tgz grpc-1.46.3.tgz
RUN pecl install grpc-1.46.3.tgz > /dev/null
RUN docker-php-ext-enable grpc
RUN apt-get install -y unzip