<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.OrderResponse</code>
 */
class OrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.finance.Alipay alipay = 1;</code>
     */
    private $alipay = null;
    /**
     * Generated from protobuf field <code>.finance.Wechat wechat = 2;</code>
     */
    private $wechat = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Finance\Alipay $alipay
     *     @type \Finance\Wechat $wechat
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.finance.Alipay alipay = 1;</code>
     * @return \Finance\Alipay
     */
    public function getAlipay()
    {
        return $this->alipay;
    }

    /**
     * Generated from protobuf field <code>.finance.Alipay alipay = 1;</code>
     * @param \Finance\Alipay $var
     * @return $this
     */
    public function setAlipay($var)
    {
        GPBUtil::checkMessage($var, \Finance\Alipay::class);
        $this->alipay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finance.Wechat wechat = 2;</code>
     * @return \Finance\Wechat
     */
    public function getWechat()
    {
        return $this->wechat;
    }

    /**
     * Generated from protobuf field <code>.finance.Wechat wechat = 2;</code>
     * @param \Finance\Wechat $var
     * @return $this
     */
    public function setWechat($var)
    {
        GPBUtil::checkMessage($var, \Finance\Wechat::class);
        $this->wechat = $var;

        return $this;
    }

}

