<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.Wechat</code>
 */
class Wechat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.finance.WechatConfig config = 1;</code>
     */
    private $config = null;
    /**
     * Generated from protobuf field <code>.finance.WechatPay pay = 2;</code>
     */
    private $pay = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Finance\WechatConfig $config
     *     @type \Finance\WechatPay $pay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.finance.WechatConfig config = 1;</code>
     * @return \Finance\WechatConfig
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Generated from protobuf field <code>.finance.WechatConfig config = 1;</code>
     * @param \Finance\WechatConfig $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Finance\WechatConfig::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.finance.WechatPay pay = 2;</code>
     * @return \Finance\WechatPay
     */
    public function getPay()
    {
        return $this->pay;
    }

    /**
     * Generated from protobuf field <code>.finance.WechatPay pay = 2;</code>
     * @param \Finance\WechatPay $var
     * @return $this
     */
    public function setPay($var)
    {
        GPBUtil::checkMessage($var, \Finance\WechatPay::class);
        $this->pay = $var;

        return $this;
    }

}

