<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto

namespace Finance;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>finance.WechatPay</code>
 */
class WechatPay extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 timeStamp = 1;</code>
     */
    private $timeStamp = 0;
    /**
     * Generated from protobuf field <code>string package = 2;</code>
     */
    private $package = '';
    /**
     * Generated from protobuf field <code>string sign = 3;</code>
     */
    private $sign = '';
    /**
     * Generated from protobuf field <code>string sign_type = 4;</code>
     */
    private $sign_type = '';
    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     */
    private $app_id = '';
    /**
     * Generated from protobuf field <code>string noncestr = 6;</code>
     */
    private $noncestr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $timeStamp
     *     @type string $package
     *     @type string $sign
     *     @type string $sign_type
     *     @type string $app_id
     *     @type string $noncestr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 timeStamp = 1;</code>
     * @return int
     */
    public function getTimeStamp()
    {
        return $this->timeStamp;
    }

    /**
     * Generated from protobuf field <code>int32 timeStamp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string package = 2;</code>
     * @return string
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Generated from protobuf field <code>string package = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sign = 3;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * Generated from protobuf field <code>string sign = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sign_type = 4;</code>
     * @return string
     */
    public function getSignType()
    {
        return $this->sign_type;
    }

    /**
     * Generated from protobuf field <code>string sign_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignType($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string noncestr = 6;</code>
     * @return string
     */
    public function getNoncestr()
    {
        return $this->noncestr;
    }

    /**
     * Generated from protobuf field <code>string noncestr = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNoncestr($var)
    {
        GPBUtil::checkString($var, True);
        $this->noncestr = $var;

        return $this;
    }

}

